    pipeline {
    agent any
    option {
        timestamps()
        timeout(time : 1, unit: "MINUTES")
    }
    stages {
        stage ('Print Date'){
            steps{
                echo "today is 04-02-2024"
            }
        }
    }
}