    pipeline {
    agent any
    options {
        timestamps()
        timeout(time : 1, unit: "MINUTES")
    }
    stages {
        stage ('Print Date'){
                echo "today is 04-02-2024"
        }
    }
}